-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 10:06:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema LittleLemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `LittleLemon` ;

-- -----------------------------------------------------
-- Table `LittleLemon`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`tables` (
  `table_no` INT NOT NULL,
  `max_guests_nb` INT NULL DEFAULT NULL,
  PRIMARY KEY (`table_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`customers` (
  `customer_id` VARCHAR(100) NOT NULL,
  `customer_first_name` VARCHAR(100) NULL DEFAULT NULL,
  `customer_last_name` VARCHAR(100) NULL DEFAULT NULL,
  `postcode` VARCHAR(100) NULL DEFAULT NULL,
  `country_code` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`staff` (
  `staff_id` INT NOT NULL,
  `staff_first_name` VARCHAR(100) NULL DEFAULT NULL,
  `staff_last_name` VARCHAR(100) NULL DEFAULT NULL,
  `staff_role` VARCHAR(100) NULL DEFAULT NULL,
  `staff_salary` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`bookings` (
  `booking_id` INT NOT NULL,
  `table_no` INT NULL DEFAULT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  `booking_date` DATE NULL DEFAULT NULL,
  `booking_time` TIME NULL DEFAULT NULL,
  `customer_id` VARCHAR(100) NULL DEFAULT NULL,
  INDEX `fk_bookings_tables1_idx` (`table_no` ASC) VISIBLE,
  INDEX `fk_bookings_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_bookings_staff1_idx` (`staff_id` ASC) VISIBLE,
  PRIMARY KEY (`booking_id`),
  CONSTRAINT `fk_bookings_tables1`
    FOREIGN KEY (`table_no`)
    REFERENCES `LittleLemon`.`tables` (`table_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemon`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `LittleLemon`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`courses` (
  `name` VARCHAR(100) NOT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `prep_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`deliveries` (
  `delivery_id` INT NOT NULL,
  `delivery_date` DATE NULL DEFAULT NULL,
  `delivery_status` VARCHAR(100) NULL DEFAULT NULL,
  `order_id` VARCHAR(100) NULL DEFAULT NULL,
  `delivery_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`delivery_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`desserts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`desserts` (
  `name` VARCHAR(100) NOT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `prep_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`drinks` (
  `name` VARCHAR(100) NOT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `prep_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`starters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`starters` (
  `name` VARCHAR(100) NOT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `prep_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`sides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`sides` (
  `name` VARCHAR(100) NOT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `prep_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`menus` (
  `menu_name` VARCHAR(100) NOT NULL,
  `cuisine` VARCHAR(100) NULL DEFAULT NULL,
  `starter` VARCHAR(100) NULL DEFAULT NULL,
  `course` VARCHAR(100) NULL DEFAULT NULL,
  `dessert` VARCHAR(100) NULL DEFAULT NULL,
  `drink` VARCHAR(100) NULL DEFAULT NULL,
  `side` VARCHAR(100) NULL DEFAULT NULL,
  INDEX `fk_menus_starters1_idx` (`starter` ASC) VISIBLE,
  INDEX `fk_menus_courses1_idx` (`course` ASC) VISIBLE,
  INDEX `fk_menus_sides1_idx` (`side` ASC) VISIBLE,
  INDEX `fk_menus_drinks1_idx` (`drink` ASC) VISIBLE,
  INDEX `fk_menus_desserts1_idx` (`dessert` ASC) VISIBLE,
  PRIMARY KEY (`menu_name`),
  CONSTRAINT `fk_menus_starters1`
    FOREIGN KEY (`starter`)
    REFERENCES `LittleLemon`.`starters` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_courses1`
    FOREIGN KEY (`course`)
    REFERENCES `LittleLemon`.`courses` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_sides1`
    FOREIGN KEY (`side`)
    REFERENCES `LittleLemon`.`sides` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_drinks1`
    FOREIGN KEY (`drink`)
    REFERENCES `LittleLemon`.`drinks` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_desserts1`
    FOREIGN KEY (`dessert`)
    REFERENCES `LittleLemon`.`desserts` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LittleLemon`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon`.`orders` (
  `order_id` VARCHAR(100) NOT NULL,
  `customer_id` VARCHAR(100) NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `sales` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `discount` DECIMAL(10,2) NULL DEFAULT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  `menu_name` VARCHAR(100) NULL DEFAULT NULL,
  `delivery_id` INT NULL,
  INDEX `fk_orders_menus_idx` (`menu_name` ASC) VISIBLE,
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_orders_staff1_idx` (`staff_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_deliveries1_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_menus`
    FOREIGN KEY (`menu_name`)
    REFERENCES `LittleLemon`.`menus` (`menu_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_deliveries1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `LittleLemon`.`deliveries` (`delivery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemon`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `LittleLemon`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
